apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-one
  name: demo-one
spec:
  type: LoadBalancer
  selector:
    app: demo-one
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP