global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'loom-demo'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['loom-demo:8080']
  - job_name: "node-exporter"
    scrape_interval: "10s"
    static_configs:
      - targets: ['node-exporter:9100']
