version: "3.8"
services:
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee-service
      MYSQL_USER: backend
      MYSQL_PASSWORD: password
