version: '3.8'
services:
  demo-app:
    image: dhananjay12/demo-app-java-21:latest
    container_name: demo-app
    ports:
      - "8080:8080"
    environment:
      - test=test
#      - spring.threads.virtual.enabled=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M